class SuggestionData {
  static Set<String> foodItems = {
    "Mele",
    "Cioccolato fondente",
    "Acqua minerale",
    "Latte",
    "Uova",
    "Burro",
    "Yogurt",
    "Formaggio",
    "Prosciutto cotto",
    "Prosciutto crudo",
    "Salame",
    "Pasta",
    "Riso",
    "Farina",
    "Zucchero",
    "Sale",
    "Olio d'oliva",
    "Aceto",
    "Sugo",
    "Pelati",
    "Tonno in scatola",
    "Legumi in scatola",
    "Mais in scatola",
    "Caffè",
    "Tè",
    "Cereali",
    "Biscotti",
    "Merendine",
    "Cioccolato",
    "Caramelle",
    "Gelato",
    "Surgelati",
    "Verdure surgelate",
    "Pesce surgelato",
    "Patate",
    "Cipolle",
    "Aglio",
    "Pomodori",
    "Insalata",
    "Carote",
    "Zucchine",

    "Arance",
    "Pere",
    "Limoni",
    "Fragole",
    "Carne bovina",
    "Pollo",
    "Maiale",
    "Hamburger",
    "Salsicce",
    "Würstel",
    "Pane",
    "Grissini",
    "Crackers",
    "Fette biscottate",
    "Marmellata",
    "Miele",
    "Nutella",
    "Dado da brodo",
    "Sapone per mani",
    "Shampoo",
    "Bagnoschiuma",
    "Dentifricio",
    "Spazzolino da denti",
    "Detersivo per piatti",
    "Detersivo per lavatrice",
    "Ammorbidente",
    "Carta igienica",
    "Fazzoletti di carta",
    "Pellicola trasparente",
    "Carta forno",
    "Sacchetti per freezer",
    "Sacchetti per spazzatura",
    "Sapone per lavastoviglie",
    "Candele",
    "Accendini",
    "Batterie",
    "Spugne",
    "Guanti",

    "Succo di frutta",
    "Bibite gassate",
    "Vino",
    "Birra",
    "Succhi di frutta",
    "Olio di semi",
    "Sale grosso",
    "Banane",
    "Frutti di Bosco",

    "Pepe",
    "Spezie",
    "Erbe aromatiche",
    "Lievito",
  };
}
